### ISSUE TITLE
Значения признаков в датасете

### ISSUE THREAD

**Issue by EgoVed** [NTech-Lab/findface#1]
Добрый день!
Ко мне на работе попала база findface
Хочу задать вопросы по параметрам базы findface.
Нужно определние значений базы:
-Верх лица
-Левый край лица
-Лицо
-Низ лица
-Первый край лица
-Уверенность (Это вероятность совпадения по фото?). Почти везде 0- это значит, что не загружены фотографии в базе для обучения?
-Время наблюдения (это длительность или что?)
-Идентификатор досье
-Идентификатор события (Какие еще бывают события) или это просто уникальный id события? 

Не github не нашел.Где это все можно посмотреть?
Спасибо!

**Comment by Alonenail** [comment]
Здравствуйте, техническая поддержка по продуктам компании производится по почте support@ntechlab.com
